module J1939Data
  ( sourceAddressTable
  ) where

import Data.Word

{- listing preferred addresses for 
 -  Industry Group #1: On-Highway Equipment
 -}

sourceAddressTable :: [(Word8, String)]
sourceAddressTable =
  [ (   0, "Engine #1" )
  , (   1, "Engine #2" )
  , (   2, "Turbocharger" )
  , (   3, "Transmission #1" )
  , (   4, "Transmission #2" )
  , (   5, "Shift Console – Primary" )
  , (   6, "Shift Console – Secondary" )
  , (   7, "Power TakeOff - (Main or Rear)" )
  , (   8, "Axle – Steering" )
  , (   9, "Axle - Drive #1" )
  , (  10, "Axle - Drive #2" )
  , (  11, "Brakes - System Controller" )
  , (  12, "Brakes - Steer Axle" )
  , (  13, "Brakes - Drive axle #1" )
  , (  14, "Brakes - Drive Axle #2" )
  , (  15, "Retarder – Engine" )
  , (  16, "Retarder – Driveline" )
  , (  17, "Cruise Control" )
  , (  18, "Fuel System" )
  , (  19, "Steering Controller" )
  , (  20, "Suspension – Steer Axle" )
  , (  21, "Suspension – Drive Axle #1" )
  , (  22, "Suspension – Drive Axle #2" )
  , (  23, "Instrument Cluster" )
  , (  24, "Trip Recorder" )
  , (  25, "Passenger-Operator Climate Control" )
  , (  26, "Electrical Charging System" )
  , (  27, "Aerodynamic Control" )
  , (  28, "Vehicle Navigation" )
  , (  29, "Vehicle Security" )
  , (  30, "Electrical System" )
  , (  31, "Starter System" )
  , (  32, "Tractor-Trailer Bridge #1" )
  , (  33, "Body Controller" )
  , (  34, "Auxiliary Valve Control" )
  , (  35, "Hitch Control" )
  , (  36, "Power TakeOff (Front or Secondary)" )
  , (  37, "Off Vehicle Gateway" )
  , (  38, "Virtual Terminal (in cab)" )
  , (  39, "Management Computer #1" )
  , (  40, "Cab Display" )
  , (  41, "Retarder, Exhaust, Engine #1" )
  , (  42, "Headway Controller" )
  , (  43, "On-Board Diagnostic Unit" )
  , (  44, "Retarder, Exhaust, Engine #2" )
  , (  45, "Endurance Braking System" )
  , (  46, "Hydraulic Pump Controller" )
  , (  47, "Suspension - System Controller #1" )
  , (  48, "Pneumatic - System Controller" )
  , (  49, "Cab Controller - Primary" )
  , (  50, "Cab Controller - Secondary" )
  , (  51, "Tire Pressure Controller" )
  , (  52, "Ignition Control Module #1" )
  , (  53, "Ignition Control Module #2" )
  , (  54, "Seat Controls" )
  , (  55, "Lighting - Operator Controls" )
  , (  56, "Rear Axle Steering Controller #1" )
  , (  57, "Water Pump Controller" )
  , (  58, "Passenger-Operator Climate Control #2" )
  , (  59, "Transmission Display - Primary" )
  , (  60, "Transmission Display - Secondary" )
  , (  61, "Exhaust Emission Controller" )
  , (  62, "Vehicle Dynamic Stability Controller" )
  , (  63, "Oil Sensor" )
  , (  64, "Suspension - System Controller #2" )
  , (  65, "Information System Controller #1" )
  , (  66, "Ramp Control" )
  , (  67, "Clutch/Converter Controller" )
  , (  68, "Auxiliary Heater #1" )
  , (  69, "Auxiliary Heater #2" )
  , (  70, "Electronic Engine Valve Controller" )
  , (  71, "Reserved for future assignment by SAE" )
  , (  72, "Reserved for future assignment by SAE" )
  , (  73, "Reserved for future assignment by SAE" )
  , (  74, "Reserved for future assignment by SAE" )
  , (  75, "Reserved for future assignment by SAE" )
  , (  76, "Reserved for future assignment by SAE" )
  , (  77, "Reserved for future assignment by SAE" )
  , (  78, "Reserved for future assignment by SAE" )
  , (  79, "Reserved for future assignment by SAE" )
  , (  80, "Reserved for future assignment by SAE" )
  , (  81, "Reserved for future assignment by SAE" )
  , (  82, "Reserved for future assignment by SAE" )
  , (  83, "Reserved for future assignment by SAE" )
  , (  84, "Reserved for future assignment by SAE" )
  , (  85, "Reserved for future assignment by SAE" )
  , (  86, "Reserved for future assignment by SAE" )
  , (  87, "Reserved for future assignment by SAE" )
  , (  88, "Reserved for future assignment by SAE" )
  , (  89, "Reserved for future assignment by SAE" )
  , (  90, "Reserved for future assignment by SAE" )
  , (  91, "Reserved for future assignment by SAE" )
  , (  92, "Reserved for future assignment by SAE" )
  , (  93, "Reserved for future assignment by SAE" )
  , (  94, "Reserved for future assignment by SAE" )
  , (  95, "Reserved for future assignment by SAE" )
  , (  96, "Reserved for future assignment by SAE" )
  , (  97, "Reserved for future assignment by SAE" )
  , (  98, "Reserved for future assignment by SAE" )
  , (  99, "Reserved for future assignment by SAE" )
  , ( 100, "Reserved for future assignment by SAE" )
  , ( 101, "Reserved for future assignment by SAE" )
  , ( 102, "Reserved for future assignment by SAE" )
  , ( 103, "Reserved for future assignment by SAE" )
  , ( 104, "Reserved for future assignment by SAE" )
  , ( 105, "Reserved for future assignment by SAE" )
  , ( 106, "Reserved for future assignment by SAE" )
  , ( 107, "Reserved for future assignment by SAE" )
  , ( 108, "Reserved for future assignment by SAE" )
  , ( 109, "Reserved for future assignment by SAE" )
  , ( 110, "Reserved for future assignment by SAE" )
  , ( 111, "Reserved for future assignment by SAE" )
  , ( 112, "Reserved for future assignment by SAE" )
  , ( 113, "Reserved for future assignment by SAE" )
  , ( 114, "Reserved for future assignment by SAE" )
  , ( 115, "Reserved for future assignment by SAE" )
  , ( 116, "Reserved for future assignment by SAE" )
  , ( 117, "Reserved for future assignment by SAE" )
  , ( 118, "Reserved for future assignment by SAE" )
  , ( 119, "Reserved for future assignment by SAE" )
  , ( 120, "Reserved for future assignment by SAE" )
  , ( 121, "Reserved for future assignment by SAE" )
  , ( 122, "Reserved for future assignment by SAE" )
  , ( 123, "Reserved for future assignment by SAE" )
  , ( 124, "Reserved for future assignment by SAE" )
  , ( 125, "Reserved for future assignment by SAE" )
  , ( 126, "Reserved for future assignment by SAE" )
  , ( 127, "Reserved for future assignment by SAE" )
  , ( 128, "Reserved for self-configurabel ECUs" )
  , ( 129, "Reserved for self-configurabel ECUs" )
  , ( 130, "Reserved for self-configurabel ECUs" )
  , ( 131, "Reserved for self-configurabel ECUs" )
  , ( 132, "Reserved for self-configurabel ECUs" )
  , ( 133, "Reserved for self-configurabel ECUs" )
  , ( 134, "Reserved for self-configurabel ECUs" )
  , ( 135, "Reserved for self-configurabel ECUs" )
  , ( 136, "Reserved for self-configurabel ECUs" )
  , ( 137, "Reserved for self-configurabel ECUs" )
  , ( 138, "Reserved for self-configurabel ECUs" )
  , ( 139, "Reserved for self-configurabel ECUs" )
  , ( 140, "Reserved for self-configurabel ECUs" )
  , ( 141, "Reserved for self-configurabel ECUs" )
  , ( 142, "Reserved for self-configurabel ECUs" )
  , ( 143, "Reserved for self-configurabel ECUs" )
  , ( 144, "Reserved for self-configurabel ECUs" )
  , ( 145, "Reserved for self-configurabel ECUs" )
  , ( 146, "Reserved for self-configurabel ECUs" )
  , ( 147, "Reserved for self-configurabel ECUs" )
  , ( 148, "Reserved for self-configurabel ECUs" )
  , ( 149, "Reserved for self-configurabel ECUs" )
  , ( 150, "Reserved for self-configurabel ECUs" )
  , ( 151, "Reserved for self-configurabel ECUs" )
  , ( 152, "Reserved for self-configurabel ECUs" )
  , ( 153, "Reserved for self-configurabel ECUs" )
  , ( 154, "Reserved for self-configurabel ECUs" )
  , ( 155, "Reserved for self-configurabel ECUs" )
  , ( 156, "Reserved for self-configurabel ECUs" )
  , ( 157, "Reserved for self-configurabel ECUs" )
  , ( 158, "Reserved for self-configurabel ECUs" )
  , ( 159, "Reserved for self-configurabel ECUs" )
  , ( 160, "Reserved for self-configurabel ECUs" )
  , ( 161, "Reserved for self-configurabel ECUs" )
  , ( 162, "Reserved for self-configurabel ECUs" )
  , ( 163, "Reserved for self-configurabel ECUs" )
  , ( 164, "Reserved for self-configurabel ECUs" )
  , ( 165, "Reserved for self-configurabel ECUs" )
  , ( 166, "Reserved for self-configurabel ECUs" )
  , ( 167, "Reserved for self-configurabel ECUs" )
  , ( 168, "Trailer #5 Bridge" )
  , ( 169, "Trailer #5 Lighting-electrical" )
  , ( 170, "Trailer #5 Brakes (ABS-EBS)" )
  , ( 171, "Trailer #5 Reefer" )
  , ( 172, "Trailer #5 Cargo" )
  , ( 173, "Trailer #5 Chassis-Suspension" )
  , ( 174, "Other Trailer #5 Devices" )
  , ( 175, "Other Trailer #5 Devices" )
  , ( 176, "Trailer #4 Bridge" )
  , ( 177, "Trailer #4 Lighting-electrical" )
  , ( 178, "Trailer #4 Brakes (ABS-EBS)" )
  , ( 179, "Trailer #4 Reefer" )
  , ( 180, "Trailer #4 Cargo" )
  , ( 181, "Trailer #4 Chassis-Suspension" )
  , ( 182, "Other Trailer #4 Devices" )
  , ( 183, "Other Trailer #4 Devices" )
  , ( 184, "Trailer #3 Bridge" )
  , ( 185, "Trailer #3 Lighting-electrical" )
  , ( 186, "Trailer #3 Brakes (ABS-EBS)" )
  , ( 187, "Trailer #3 Reefer" )
  , ( 188, "Trailer #3 Cargo" )
  , ( 189, "Trailer #3 Chassis-Suspension" )
  , ( 190, "Other Trailer #3 Devices" )
  , ( 191, "Other Trailer #3 Devices" )
  , ( 192, "Trailer #2 Bridge" )
  , ( 193, "Trailer #2 Lighting-electrical" )
  , ( 194, "Trailer #2 Brakes (ABS-EBS)" )
  , ( 195, "Trailer #2 Reefer" )
  , ( 196, "Trailer #2 Cargo" )
  , ( 197, "Trailer #2 Chassis-Suspension" )
  , ( 198, "Other Trailer #2 Devices" )
  , ( 199, "Other Trailer #2 Devices" )
  , ( 200, "Trailer #1 Bridge" )
  , ( 201, "Trailer #1 Lighting-electrical" )
  , ( 202, "Trailer #1 Brakes (ABS-EBS)" )
  , ( 203, "Trailer #1 Reefer" )
  , ( 204, "Trailer #1 Cargo" )
  , ( 205, "Trailer #1 Chassis-Suspension" )
  , ( 206, "Other Trailer #1 Devices" )
  , ( 207, "Other Trailer #1 Devices" )
  , ( 208, "Reserved for future assignment by SAE" )
  , ( 209, "Reserved for future assignment by SAE" )
  , ( 210, "Reserved for future assignment by SAE" )
  , ( 211, "Reserved for future assignment by SAE" )
  , ( 212, "Reserved for future assignment by SAE" )
  , ( 213, "Reserved for future assignment by SAE" )
  , ( 214, "Reserved for future assignment by SAE" )
  , ( 215, "Reserved for future assignment by SAE" )
  , ( 216, "Reserved for future assignment by SAE" )
  , ( 217, "Reserved for future assignment by SAE" )
  , ( 218, "Reserved for future assignment by SAE" )
  , ( 219, "Reserved for future assignment by SAE" )
  , ( 220, "Reserved for future assignment by SAE" )
  , ( 221, "Reserved for future assignment by SAE" )
  , ( 222, "Reserved for future assignment by SAE" )
  , ( 223, "Reserved for future assignment by SAE" )
  , ( 224, "Reserved for future assignment by SAE" )
  , ( 225, "Reserved for future assignment by SAE" )
  , ( 226, "Reserved for future assignment by SAE" )
  , ( 227, "Reserved for future assignment by SAE" )
  , ( 228, "Reserved for future assignment by SAE" )
  , ( 229, "Reserved for future assignment by SAE" )
  , ( 230, "Reserved for future assignment by SAE" )
  , ( 231, "Reserved for future assignment by SAE" )
  , ( 232, "Forward Road Image Processor" )
  , ( 233, "Door Controller # 3" )
  , ( 234, "Door Controller #4" )
  , ( 235, "Tractor/Trailer Bridge #2" )
  , ( 236, "Door Controller #1" )
  , ( 237, "Door Controller #2" )
  , ( 238, "Tachograph" )
  , ( 239, "Electric Propulsion Control Unit #1" )
  , ( 240, "Electric Propulsion Control Unit #2" )
  , ( 241, "Electric Propulsion Control Unit #3" )
  , ( 242, "Electric Propulsion Control Unit #4" )
  , ( 243, "Battery Pack Monitor #1" )
  , ( 244, "Battery Pack Monitor #2" )
  , ( 245, "Battery Pack Monitor #3" )
  , ( 246, "Battery Pack Monitor #4" )
  , ( 247, "Auxiliary Power Unit (APU)" )
  , ( 248, "Reserved for future use" )
  , ( 249, "Off Board Diagnostic-Service Tool #1" )
  , ( 250, "Off Board Diagnostic-Service Tool #2" )
  , ( 251, "On-Board Data Logger" )
  , ( 252, "Reserved for Experimental Use" )
  , ( 253, "Reserved for OEM" )
  , ( 254, "Null Address" )
  , ( 255, "GLOBAL (All-Any Node)" )
  ]
  
